config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, path: "accounts", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  resources :users do
    resources :flash_cards do
      post "compare", to: "flash_cards#compare"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
  belongs_to :user

  validates_presence_of :category, :question, :answer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flash_cards

  validates_presence_of :email, :encrypted_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    user_flash_cards_path(current_user.id)
  end
end

app/controllers/flash_cards_controller.rb
class FlashCardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @flash_cards = current_user.flash_cards.all
  end

  def new
    @flash_card = current_user.flash_cards.build
  end

  def create
    @flash_card = current_user.flash_cards.build(flash_card_params)

    if @flash_card.save
      flash[:notice] = "Criado com sucesso"
      redirect_to action: "index"
    else
      render :new
    end
  end

  def show
    @flash_card = FlashCard.find(params[:id])
  end

  def edit
    @flash_card = FlashCard.find(params[:id])
  end

  def update
    @flash_card = FlashCard.find(params[:id])

    if @flash_card.update(flash_card_params)
      flash[:notice] = "Atualizado com sucesso"
      redirect_to action: "index"
    else
      render :edit
    end
  end

  def destroy
    @flash_card = FlashCard.find(params[:id])
    @flash_card.destroy

    flash[:notice] = "The Flash Card was successfully destroyed"
    redirect_to action: "index"
  end

  def compare
    your_answer = params[:your_answer]
    @flash_card = FlashCard.find(params[:flash_card_id])

    flash[:notice] = if your_answer == @flash_card.answer
      "Você acertou"
    else
      "Você errou"
    end

    redirect_to user_flash_card_path(id: @flash_card.id)
  end

  private

  def flash_card_params
    params.require(:flash_card).permit(:category, :answer, :question, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save

    yield resource if block_given?

    if resource.persisted?
      if resource.active_for_authentication?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimun_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)

    yield resource if block_given?

    respond_with resource, location: after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))

    yield if block_given?

    respond_to_on_destroy
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_cards_helper.rb
module FlashCardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/flash_cards/edit.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-one-third-tablet is-four-fifths-mobile">
    <h2 class="is-size-3 is-size-4-mobile has-text-centered">
      Edit Flash Card
    </h2>

    <%= form_with scope: :flash_card, local: true, url: user_flash_card_path, method: "put" do |form| %>

      <% if @flash_card.errors.any? %>
        <h2>
          <%= pluralize(@flash_card.errors.count, "error") %> prohibted
          this Flash Card from being saved:
        </h2>

        <ul>
          <% @flash_card.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="field">
        <%= form.label :category, class: "label" %>
        <div class="control">
          <%= form.text_field :category, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :question, class: "label" %>
        <div class="control">
          <%= form.text_field :question, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :answer, class: "label" %>
        <div class="control">
          <%= form.text_field :answer, class: "input" %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= form.submit "Edit Flash Card", class: "button is-primary" %>
        </div>

        <div class="control">
          <%= link_to 'Back', user_flash_cards_path, class: "button is-link is-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flash_cards/index.html.erb
<div class="columns is-mobile is-centered is-multiline">
  <% if @flash_cards.empty? %>
    <h2 class="is-size-3">Você não possui nenhum Flash Card</h2>
  <% else %>
    <% @flash_cards.each do |card| %>
      <div class="column is-one-quarter-tablet is-four-fifths-mobile">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title"><%= card.category %></p>
          </header>
          <div class="card-content">
            <div class="content">
              <%= card.question %>
            </div>
          </div>
          <footer class="card-footer">
            <%= link_to "Show", user_flash_card_path(current_user, card), method: :get, class: "card-footer-item" %>
            <%= link_to "Edit", edit_user_flash_card_path(current_user, card), class: "card-footer-item" %>
            <%= link_to "Delete", user_flash_card_path(current_user, card), class: "card-footer-item", method: :delete,
              data: {
                confirm: 'Are you sure?'
              }
            %>
          </footer>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/flash_cards/new.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-one-third-tablet is-four-fifths-mobile">
    <h2 class="is-size-3 is-size-4-mobile mb-3 has-text-centered">Create a new Flash Card</h2>

    <%= form_with scope: :flash_card, local: true, url: user_flash_cards_path do |form| %>
      <% if @flash_card.errors.any? %>
        <h2>
          <%= pluralize(@flash_card.errors.count, "error") %> prohibted
          this Flash Card from being saved:
        </h2>

        <ul>
          <% @flash_card.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="field">
        <%= form.label :category, class: "label" %>
        <div class="control">
          <%= form.text_field :category, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :question, class: "label" %>
        <div class="control">
          <%= form.text_field :question, class: "input" %>
        </div>
      </div>

      <div class="field">
        <%= form.label :answer, class: "label" %>
        <div class="control">
          <%= form.text_field :answer, class: "input" %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= form.submit class: "button is-primary" %>
        </div>

        <div class="control">
          <%= link_to 'Back', user_flash_cards_path, class: "button is-link is-light" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flash_cards/show.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-one-third-tablet is-four-fifths-mobile">
    <h2 class="is-size-3 has-text-centered mb-3">
      <%= @flash_card.question %>
    </h2>

    <div class="field">
      <%= form_with local: true, url: user_flash_card_compare_path(flash_card_id: @flash_card.id) do |form| %>

        <%= form.label :your_answer, class: "label" %>
        <div class="control">
          <%= form.text_field :your_answer, class: "input" %>
        </div>
    </div>

    <div class="field is-grouped">
        <div class="control">
          <%= form.submit "Compare", class: "button is-primary" %>
        </div>
        <div class="control">
          <%= link_to "Back", user_flash_cards_path, class: "button is-link is-light" %>
        </div>
    </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container">
      <% if notice.present? %>
        <%= notice %>
      <% end %>

      <% if alert.present? %>
        <%= alert %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar is-info mb-4" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">
      <h2 class="is-size-4 has-text-weight-bold">Flash Cards</h2>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to "Create new Flash Card", new_user_flash_card_path, class: "button is-link" %>
            <%= link_to "Log out", destroy_user_session_path, class: "button is-light",
            method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>